name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-2019
    defaults:
      run:
        working-directory: docker-image/v1.10/windows/elasticsearch7
    steps:
    - name: Build and push Docker images
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: jrobertsoninsite/fluentd-kubernetes-daemonset-windows
        tags: latest
